title: blog
author: Melih Sivri
email: mlheymen.ms@gmail.com
url: https://msrexe.github.io
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Melih Sivri's personal blog. I write about software development, technology, and life. 

permalink: /:slug.html

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
goat_counter: "blog.melihsivri.dev" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "Home" # customize text for homepage link in post layout
  date_format: "%B %d, %Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
